import 'api_client.dart';

class SecurityService {
  SecurityService._();
  static final SecurityService instance = SecurityService._();

  final ApiClient _api = ApiClient.instance;

  // ─── OTP ───────────────────────────────────────────────────────────────

  Future<void> sendOtp({
    required String channel, // 'email' | 'phone'
    required String purpose, // email_verification | phone_verification | password_reset | sensitive_action
    required String identifier,
  }) async {
    await _api.post('/security/otp/send', body: {
      'channel': channel,
      'purpose': purpose,
      'identifier': identifier,
    });
  }

  Future<void> verifyOtp({
    required String identifier,
    required String code,
    required String purpose,
  }) async {
    await _api.post('/security/otp/verify', body: {
      'identifier': identifier,
      'code': code,
      'purpose': purpose,
    });
  }

  // ─── 2FA TOTP ──────────────────────────────────────────────────────────

  /// Returns { secret, uri } — show the QR (uri) to the user.
  Future<Map<String, dynamic>> start2faEnrollment() async {
    final res = await _api.post('/security/2fa/enroll');
    return Map<String, dynamic>.from(res['data'] as Map);
  }

  /// Returns the list of backup codes generated by the server.
  Future<List<String>> finish2faEnrollment(String token) async {
    final res = await _api.post('/security/2fa/enroll/verify', body: {
      'token': token,
    });
    return List<String>.from((res['data'] as Map)['backupCodes'] as List);
  }

  Future<void> verify2fa(String token) async {
    await _api.post('/security/2fa/verify', body: {'token': token});
  }

  Future<void> disable2fa() async {
    await _api.delete('/security/2fa');
  }

  // ─── Sessions ──────────────────────────────────────────────────────────

  Future<List<Map<String, dynamic>>> listSessions() async {
    final res = await _api.get('/security/sessions');
    return List<Map<String, dynamic>>.from(
      (res['data'] as List).map((e) => Map<String, dynamic>.from(e as Map)),
    );
  }

  Future<void> revokeSession(String id) async {
    await _api.delete('/security/sessions/$id');
  }

  Future<void> revokeAllSessions() async {
    await _api.post('/security/sessions/revoke-all');
  }

  // ─── Privacy ───────────────────────────────────────────────────────────

  Future<Map<String, dynamic>> updatePrivacy(Map<String, dynamic> patch) async {
    final res = await _api.patch('/security/privacy', body: patch);
    return Map<String, dynamic>.from(res['data'] as Map);
  }

  // ─── Resume access log ─────────────────────────────────────────────────

  Future<List<Map<String, dynamic>>> resumeAccessLog() async {
    final res = await _api.get('/security/resume-access-log');
    return List<Map<String, dynamic>>.from(
      (res['data'] as List).map((e) => Map<String, dynamic>.from(e as Map)),
    );
  }

  // ─── Password strength ─────────────────────────────────────────────────

  Future<Map<String, dynamic>> checkPasswordStrength(String password) async {
    final res = await _api.post(
      '/security/password/strength',
      body: {'password': password},
      auth: false,
    );
    return Map<String, dynamic>.from(res['data'] as Map);
  }
}
