// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DTlmpskhwK04Ua7r-eKsdxwtYdAcLOQ',
    appId: '1:309121341037:web:caf37904540a843d049164',
    messagingSenderId: '309121341037',
    projectId: 'job-hunter-63fdc',
    authDomain: 'job-hunter-63fdc.firebaseapp.com',
    storageBucket: 'job-hunter-63fdc.firebasestorage.app',
    measurementId: 'G-JH9V3H6JJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwAOFGH1y_sG4QH645JFMnVW4HDlJ7QZs',
    appId: '1:309121341037:android:e3a072249e7707c7049164',
    messagingSenderId: '309121341037',
    projectId: 'job-hunter-63fdc',
    storageBucket: 'job-hunter-63fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrU6tiZX-bK1qFAuQ-digV0J9LQeg2yc0',
    appId: '1:309121341037:ios:2a13dad7362a726c049164',
    messagingSenderId: '309121341037',
    projectId: 'job-hunter-63fdc',
    storageBucket: 'job-hunter-63fdc.firebasestorage.app',
    androidClientId: '309121341037-5o36mrf50ae8kslf5qp9m970h185hkjr.apps.googleusercontent.com',
    iosClientId: '309121341037-htl528ee5mtabq0thc2an56tm8k02f4f.apps.googleusercontent.com',
    iosBundleId: 'com.vinoth.jobhunter',
  );
}
