class AppRoutes {
  AppRoutes._();

  static const String splash = '/';
  static const String login = '/login';
  static const String emailAuth = '/email-auth';
  static const String forgotPassword = '/forgot-password';
  static const String rolePicker = '/role-picker';
  static const String onboarding = '/onboarding';
  static const String main = '/main';
  static const String search = '/search';
  static const String jobDetail = '/job-detail';
  static const String profileEdit = '/profile-edit';
  static const String profileInformation = '/profile-information';
  static const String resumeProfile = '/resume-profile';
  static const String editField = '/edit-field';
  static const String helpSupport = '/help-support';
  static const String about = '/about';
  static const String subscription = '/subscription';
  static const String alerts = '/alerts';
  static const String hirerProfileSetup = '/hirer-profile-setup';
  static const String hirerDashboard = '/hirer-dashboard';
  static const String hirerPostJob = '/hirer-post-job';
  static const String hirerManageJobs = '/hirer-manage-jobs';
  static const String hirerApplicants = '/hirer-applicants';
  static const String hirerKanban = '/hirer-kanban';
  static const String hirerTeam = '/hirer-team';
  static const String savedJobs = '/saved-jobs';
  static const String autoApply = '/auto-apply';
  static const String autoApplyReview = '/auto-apply-review';
  static const String autoApplyLog = '/auto-apply-log';
  static const String conversations = '/conversations';
  static const String chat = '/chat';
  static const String myInterviews = '/my-interviews';
  static const String companyProfile = '/company-profile';
  static const String profileOptimizer = '/profile-optimizer';
  static const String skillGap = '/skill-gap';
  static const String skillAssessments = '/skill-assessments';
  static const String assessmentQuiz = '/assessment-quiz';
  static const String assessmentResult = '/assessment-result';
  static const String mockInterview = '/mock-interview';
  static const String badges = '/badges';
  static const String hirerAnalytics = '/hirer-analytics';
  static const String notifications = '/notifications';
  static const String notificationPrefs = '/notification-prefs';
}
